HashTable Exercise
mmxer/OopExercise1 pull request #1
Opened 2016-10-28 17:31 UTC by mmxer

2016-10-30 15:32 UTC, yurii-litvinov requested changes

2016-10-30 15:32 UTC, yurii-litvinov commented on OopExercise1/HashFuctionExample.cs
> +    public class HashFuctionExample : IHashFuction
К самим классам, интерфейсам и т.д. тоже желательны комментарии

2016-10-30 15:32 UTC, yurii-litvinov commented on OopExercise1/HashTableArray.cs
> +        public IHashFuction HashFunction { get; set; }
Хеш-функцию лучше инициализировать в конструкторе (какой-то хеш-функцией по умолчанию, либо принимать как аргумент) иначе после конструктора хеш-таблица не готова ещё к работе и если забыть присвоить хеш-функцию, будет падать. Вообще, обычно стараются сделать так, чтобы после конструктора никакой дополнительной инициализации бы не требовалось (потому что обойти конструктор невозможно, а вот забыть сделать дополнительную инициализацию --- легко). Это, правда, не всегда возможно, например, потому, что в конструкторе нельзя вызывать виртуальные методы.

2016-10-30 15:32 UTC, yurii-litvinov commented on OopExercise1/HashTableArray.cs
> +            LinkedList<KeyValue> linkedList = this.GetLinkedList(position);
Тут объявление через var выглядело бы симпатичнее:
```csharp
var linkedList = this.GetLinkedList(position);
```

2016-10-30 15:32 UTC, yurii-litvinov commented on OopExercise1/HashTableArray.cs
> +        public IHashFuction HashFunction { get; set; }
set должен быть посложнее, потому что если мы для уже заполненной хеш-таблицы попытаемся сменить хеш-функцию, старые значения будут лежать по старым хеш-значениям и с помощью новой хеш-функции их будет не найти. Надо после смены хеш-функции пересчитать хеши для всего, что уже лежит в хеш-таблице, и переложить всё.

2016-10-30 15:32 UTC, yurii-litvinov commented on OopExercise1/HashTableArray.cs
> +        protected struct KeyValue
А зачем они все protected? Из общих соображений, наверное, это имеет смысл, но мы вряд ли будем наследоваться от этого класса. Я бы его сделал вообще sealed, чтобы не думать о возможных наследниках. А то вот наследники могут нарушать инвариант предка, получив доступ к списку и записав туда что-нибудь не то.

2016-11-02 07:05 UTC, yurii-litvinov approved these changes
Посмотрел, всё круто.

2016-11-02 07:05 UTC, yurii-litvinov commented on OopExercise1/HashTableArray.cs
> +            linkedList.AddLast(item);
Тут неплохо бы проверять, что такого ключа ещё нет, а то несколько значений с одним ключом могут стать неожиданностью для пользователей.

2016-11-02 08:16 UTC, mmxer commented on OopExercise1/HashTableArray.cs
> +            linkedList.AddLast(item);
Ужас! Сделаю проверку и тест на этот случай.

2016-11-02 10:02 UTC, merged